/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import Connector.KetNoiSQL;
import DAO.capDaiDAO;
import DAO.chuongTrinhHocDAO;
import DAO.taiLieuVideoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.capDai;
import model.chuongTrinhHoc;
import model.taiLieuVideo;
import textfield.SearchOptinEvent;
import textfield.SearchOption;

/**
 *
 * @author huuzinhh
 */
public class mainAdmin extends javax.swing.JFrame {
    private String email;
    public mainAdmin() {
        initComponents();
      
    }
    
    
    private int width=180;
    private int height=630;
    
    void openMenu(){
        new Thread(new Runnable(){
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    jPanelMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(mainAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }                   
                }
        
            }
        }).start();
    }
    void closeMenu(){
        new Thread(new Runnable(){
            @Override
            public void run() {
                for (int i = width; i >0; i--) {
                    jPanelMenu.setSize(i, height);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(mainAdmin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        
            }
        }).start();
    }
    void setnameuser(String email) {
        this.email = email;
        Connection conn = KetNoiSQL.getConnection();
        String sql = "select * from banChuNhiem,taiKhoan  where email='" + email + "'";
        try {
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next()) {
                txtusername.setText(rs.getString("tenDangNhap"));
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        trangChuAdmin = new jFrame.trangChuAdmin();
        thongTinAdmin = new jFrame.thongTinAdmin();
        diemAdmin = new jFrame.diemAdmin();
        diemDanhAdmin = new jFrame.diemDanhAdmin();
        thongTinVoSinhAdmin = new jFrame.thongTinVoSinhAdmin();
        thongTinTaiKhoanAdmin = new jFrame.thongTinTaiKhoanAdmin();
        thongBaoAdmin = new jFrame.thongBaoAdmin();
        dungCuAdmin = new jFrame.dungCuAdmin();
        donHangAdmin = new jFrame.donHangAdmin();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtusername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(180, 630));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(180, 630));

        jLabel25.setText("avatar");

        jLabel26.setText("Nguyễn Hữu Vinh");

        jLabel27.setText("Trang Chủ");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel28.setText("Thông Tin");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel29.setText("Điểm");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });

        jLabel30.setText("Điểm Danh");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setText("Đơn Hàng");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });

        jLabel32.setText("Thông Báo");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel34.setText("Đăng Xuất");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelmenu.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setText("Dụng Cụ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel11.setText("Thông tin võ sinh");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel26)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel34)
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(39, 39, 39)
                .addComponent(jLabel26)
                .addGap(45, 45, 45)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 630));

        jPanel4.setLayout(new java.awt.CardLayout());
        jPanel4.add(trangChuAdmin, "card10");
        jPanel4.add(thongTinAdmin, "card11");
        jPanel4.add(diemAdmin, "card10");
        jPanel4.add(diemDanhAdmin, "card11");
        jPanel4.add(thongTinVoSinhAdmin, "card10");
        jPanel4.add(thongTinTaiKhoanAdmin, "card10");
        jPanel4.add(thongBaoAdmin, "card10");
        jPanel4.add(dungCuAdmin, "card10");
        jPanel4.add(donHangAdmin, "card10");

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 950, 560));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jLabel12.setText("MENU");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 20, 40));

        txtusername.setForeground(new java.awt.Color(255, 255, 51));
        txtusername.setText("Nguyễn Hữu Vinh");
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, -1, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        closeMenu();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        openMenu();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(true);
        thongTinAdmin.showTableCTH();
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(true);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
        
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(true);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(true);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(true);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(true);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        int test = JOptionPane.showConfirmDialog(null, "Bạn chắc có muốn đăng xuất hay không !", "Thông báo đăng nhập", JOptionPane.YES_NO_OPTION);
        if (test == JOptionPane.YES_OPTION) {
            dispose();
//            Login login = new Login();
//            login.show();
        } else if (test == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã hủy đăng xuất");
        }        
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(true);
        thongTinVoSinhAdmin.setVisible(false);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        diemAdmin.setVisible(false);
        diemDanhAdmin.setVisible(false);
        donHangAdmin.setVisible(false);
        dungCuAdmin.setVisible(false);
        thongBaoAdmin.setVisible(false);
        thongTinAdmin.setVisible(false);
        thongTinTaiKhoanAdmin.setVisible(false);
        thongTinVoSinhAdmin.setVisible(true);
        trangChuAdmin.setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainAdmin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jFrame.diemAdmin diemAdmin;
    private jFrame.diemDanhAdmin diemDanhAdmin;
    private jFrame.donHangAdmin donHangAdmin;
    private jFrame.dungCuAdmin dungCuAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelMenu;
    private jFrame.thongBaoAdmin thongBaoAdmin;
    private jFrame.thongTinAdmin thongTinAdmin;
    private jFrame.thongTinTaiKhoanAdmin thongTinTaiKhoanAdmin;
    private jFrame.thongTinVoSinhAdmin thongTinVoSinhAdmin;
    private jFrame.trangChuAdmin trangChuAdmin;
    private javax.swing.JLabel txtusername;
    // End of variables declaration//GEN-END:variables


   

}
