/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jFrame;


import DAO.capDaiDAO;
import DAO.chuongTrinhHocDAO;
import DAO.taiLieuVideoDAO;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.capDai;
import model.chuongTrinhHoc;
import model.taiLieuVideo;
import textfield.SearchOptinEvent;
import textfield.SearchOption;

/**
 *
 * @author huuzinhh
 */
public class thongTinAdmin extends javax.swing.JPanel {


    private List<capDai> listCD;
    private List<chuongTrinhHoc> listCTH;
    private List<taiLieuVideo> listTLV;
    private DefaultTableModel ModelCTH;
    private DefaultTableModel ModelCD;
    private DefaultTableModel ModelTLV;
    private int count = -1;
    public thongTinAdmin() {
        initComponents();
        AddSearchCTH();
        AddSearchCD();
        AddSearchTLV();
        ModelCTH = (DefaultTableModel) tableCTH.getModel();
        ModelCD = (DefaultTableModel) tableCD.getModel();
        ModelTLV = (DefaultTableModel) tableTLV.getModel();
        showTableCTH();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelThongTinCD = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCD = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        txtSearchCD = new textfield.TextFieldSearchOption();
        jPanelThongTinTL = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTLV = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        txtSearchTLV = new textfield.TextFieldSearchOption();
        jPanelThongTinCTTL = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableCTH = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        txtSearchCTH = new textfield.TextFieldSearchOption();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.CardLayout());

        tableCD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cấp", "Bậc", "Màu đai", "Danh Xưng", "Thời Gian"
            }
        ));
        jScrollPane2.setViewportView(tableCD);

        jButton9.setText("Thêm");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Chỉnh Sửa");

        jButton11.setText("Xóa");

        jButton12.setText("Xem Chi Tiết");

        txtSearchCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongTinCDLayout = new javax.swing.GroupLayout(jPanelThongTinCD);
        jPanelThongTinCD.setLayout(jPanelThongTinCDLayout);
        jPanelThongTinCDLayout.setHorizontalGroup(
            jPanelThongTinCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanelThongTinCDLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton9)
                .addGap(73, 73, 73)
                .addComponent(jButton10)
                .addGap(91, 91, 91)
                .addComponent(jButton11)
                .addGap(81, 81, 81)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(txtSearchCD, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelThongTinCDLayout.setVerticalGroup(
            jPanelThongTinCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinCDLayout.createSequentialGroup()
                .addGroup(jPanelThongTinCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinCDLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelThongTinCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addComponent(jButton12)))
                    .addComponent(txtSearchCD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanelThongTinCD, "card2");

        tableTLV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên Bài", "link"
            }
        ));
        jScrollPane3.setViewportView(tableTLV);

        jButton13.setText("Thêm");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Chỉnh Sửa");

        jButton15.setText("Xóa");

        jButton16.setText("Xem Chi Tiết");

        txtSearchTLV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchTLVKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongTinTLLayout = new javax.swing.GroupLayout(jPanelThongTinTL);
        jPanelThongTinTL.setLayout(jPanelThongTinTLLayout);
        jPanelThongTinTLLayout.setHorizontalGroup(
            jPanelThongTinTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanelThongTinTLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton13)
                .addGap(73, 73, 73)
                .addComponent(jButton14)
                .addGap(91, 91, 91)
                .addComponent(jButton15)
                .addGap(81, 81, 81)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(txtSearchTLV, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelThongTinTLLayout.setVerticalGroup(
            jPanelThongTinTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinTLLayout.createSequentialGroup()
                .addGroup(jPanelThongTinTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinTLLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanelThongTinTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13)
                            .addComponent(jButton14)
                            .addComponent(jButton15)
                            .addComponent(jButton16)))
                    .addComponent(txtSearchTLV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanelThongTinTL, "card2");

        tableCTH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cấp", "Quyền", "Thế", "Thể Lực", "Lí Luận Võ Học", "Lí Luận Võ Đạo"
            }
        ));
        jScrollPane4.setViewportView(tableCTH);

        jButton17.setText("Thêm");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Chỉnh Sửa");

        jButton19.setText("Xóa");

        jButton20.setText("Xem Chi Tiết");

        txtSearchCTH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCTHKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelThongTinCTTLLayout = new javax.swing.GroupLayout(jPanelThongTinCTTL);
        jPanelThongTinCTTL.setLayout(jPanelThongTinCTTLLayout);
        jPanelThongTinCTTLLayout.setHorizontalGroup(
            jPanelThongTinCTTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(jPanelThongTinCTTLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton17)
                .addGap(73, 73, 73)
                .addComponent(jButton18)
                .addGap(91, 91, 91)
                .addComponent(jButton19)
                .addGap(81, 81, 81)
                .addComponent(jButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(txtSearchCTH, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelThongTinCTTLLayout.setVerticalGroup(
            jPanelThongTinCTTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinCTTLLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelThongTinCTTLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jButton19)
                    .addComponent(jButton20)
                    .addComponent(txtSearchCTH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanelThongTinCTTL, "card2");

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 950, 470));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Quản lí trang thông tin");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        jButton6.setText("Cấp đai");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Chương trình tập luyện");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Tài liệu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(0, 643, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 950, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtSearchCDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCDKeyReleased
        // TODO add your handling code here:
        if (txtSearchCD.isSelected()) {
            int option = txtSearchCD.getSelectedIndex();
            String textsearch = txtSearchCD.getText().trim();
            if (option == 0) {
                showTableCD("cap", textsearch);
            } else if (option == 1) {
                showTableCD("bac", textsearch);
            } else if (option == 2) {
                showTableCD("mauDai", textsearch);
            } else if (option == 3) {
                showTableCD("danhXung", textsearch);
            } else if (option == 4) {
                showTableCD("thoiGian", textsearch);
            }
        }        
    }//GEN-LAST:event_txtSearchCDKeyReleased

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txtSearchTLVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTLVKeyReleased
        // TODO add your handling code here:
        if (txtSearchTLV.isSelected()) {
            int option = txtSearchTLV.getSelectedIndex();
            String textsearch = txtSearchTLV.getText().trim();
            if (option == 0) {
                showTableTLV("tenBai", textsearch);
            } 
        }        
    }//GEN-LAST:event_txtSearchTLVKeyReleased

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void txtSearchCTHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCTHKeyReleased
        // TODO add your handling code here:
            if (txtSearchCTH.isSelected()) {
            int option = txtSearchCTH.getSelectedIndex();
            String textsearch = txtSearchCTH.getText().trim();
            if (option == 0) {
                showTableCD("cap", textsearch);
            } else if (option == 1) {
                showTableCD("quyen", textsearch);
            } else if (option == 2) {
                showTableCD("the", textsearch);
            } else if (option == 3) {
                showTableCD("theLuc", textsearch);
            } else if (option == 4) {
                showTableCD("liLuanVoHoc", textsearch);
            } else if (option == 5) {
                showTableCD("liLuanVoDao", textsearch);
            }
        }   
    }//GEN-LAST:event_txtSearchCTHKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanelThongTinCD.setVisible(true);
        jPanelThongTinCTTL.setVisible(false);
        jPanelThongTinTL.setVisible(false);
        showTableCD();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jPanelThongTinCD.setVisible(false);
        jPanelThongTinCTTL.setVisible(true);
        jPanelThongTinTL.setVisible(false);
        showTableCTH();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jPanelThongTinCD.setVisible(false);
        jPanelThongTinCTTL.setVisible(false);
        jPanelThongTinTL.setVisible(true);
        showTableTLV();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelThongTinCD;
    private javax.swing.JPanel jPanelThongTinCTTL;
    private javax.swing.JPanel jPanelThongTinTL;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableCD;
    private javax.swing.JTable tableCTH;
    private javax.swing.JTable tableTLV;
    private textfield.TextFieldSearchOption txtSearchCD;
    private textfield.TextFieldSearchOption txtSearchCTH;
    private textfield.TextFieldSearchOption txtSearchTLV;
    // End of variables declaration//GEN-END:variables

    void showTableCTH() {
        listCTH = new chuongTrinhHocDAO().getAllThongTinCTH();        
        ModelCTH.setRowCount(0);
        for (chuongTrinhHoc cth : listCTH) {
            int sl = new chuongTrinhHocDAO().SoLuongCTH();
            ModelCTH.addRow(new Object[]{
                cth.getCap(),cth.getQuyen(),cth.getThe(),cth.getTheLuc(),cth.getLiLuanVoHoc(),cth.getLiLuanVoDao()
            });
        }
        count = -1;
    }

     private void showTableCTH(String where, String text) {
        listCTH = new chuongTrinhHocDAO().getAllThongTinCTHSearch( where,  text);        
        ModelCTH.setRowCount(0);
        for (chuongTrinhHoc cth : listCTH) {
            int sl = new chuongTrinhHocDAO().SoLuongCTH();
            ModelCTH.addRow(new Object[]{
                cth.getCap(),cth.getQuyen(),cth.getThe(),cth.getTheLuc(),cth.getLiLuanVoHoc(),cth.getLiLuanVoDao()
            });
        }
    }

//     private void showTableViewCTH(String maPhong) {
//        listsinhvien = new SinhVienDAO().getAllThongTinSVTheoPhong(maPhong);
//        TableView.setRowCount(0);
//        for (ThongTinSinhVien sv : listsinhvien) {
//            TableView.addRow(new Object[]{
//                sv.getMaSV(), sv.getTenSV(), sv.getCCCD(), sv.getGioiTinh(), sv.getNgaySinh(), sv.getMaLop(), sv.getSoDienThoai()
//            });
//        }
//    }
   void showTableCD() {
        listCD = new capDaiDAO().getAllThongTinCD();        
        ModelCD.setRowCount(0);
        for (capDai cd : listCD) {
            int sl = new capDaiDAO().SoLuongCD();
            ModelCD.addRow(new Object[]{
                cd.getCap(),cd.getBac(),cd.getMauDai(),cd.getDanhXung(),cd.getThoiGian()
            });
        }
        count = -1;
    }

     private void showTableCD(String where, String text) {
        listCD = new capDaiDAO().getAllThongTinCDSearch( where,  text);             
        ModelCD.setRowCount(0);
        for (capDai cd : listCD) {
            int sl = new capDaiDAO().SoLuongCD();
            ModelCD.addRow(new Object[]{
                cd.getCap(),cd.getBac(),cd.getMauDai(),cd.getDanhXung(),cd.getThoiGian()
            });
        }
    }   
     void showTableTLV() {
        listTLV = new taiLieuVideoDAO().getAllThongTinTLV();        
        ModelTLV.setRowCount(0);
        for (taiLieuVideo tlv : listTLV) {
            int sl = new taiLieuVideoDAO().SoLuongTLV();
            ModelTLV.addRow(new Object[]{
                tlv.getId(),tlv.getTenBai(),tlv.getLinkVideo()
            });
        }
        count = -1;
    }

     private void showTableTLV(String where, String text) {
        listTLV = new taiLieuVideoDAO().getAllThongTinTLVSearch( where,  text);    
        ModelTLV.setRowCount(0);
        for (taiLieuVideo tlv : listTLV) {
            int sl = new taiLieuVideoDAO().SoLuongTLV();
            ModelTLV.addRow(new Object[]{
                tlv.getId(),tlv.getTenBai(),tlv.getLinkVideo()
            });
        }
    }
    void AddSearchCTH() {
        txtSearchTLV.addEventOptionSelected(new SearchOptinEvent() {
            @Override
            public void optionSelected(SearchOption option, int index) {
                txtSearchCTH.setHint("Tìm kiếm " + option.getName() + "....");
            }
        });
        txtSearchTLV.addOption(new SearchOption("cấp", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchTLV.addOption(new SearchOption("quyền", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchTLV.addOption(new SearchOption("thế", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchTLV.addOption(new SearchOption("thể lực", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchTLV.addOption(new SearchOption("Lí luận võ học", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchTLV.addOption(new SearchOption("Lí luận võ đạo", new ImageIcon(getClass().getResource("/img/user.png"))));

    }
    void AddSearchCD() {
        txtSearchCD.addEventOptionSelected(new SearchOptinEvent() {
            @Override
            public void optionSelected(SearchOption option, int index) {
                txtSearchCD.setHint("Tìm kiếm " + option.getName() + "....");
            }
        });
        txtSearchCD.addOption(new SearchOption("cấp", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchCD.addOption(new SearchOption("bậc", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchCD.addOption(new SearchOption("màu đai", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchCD.addOption(new SearchOption("danh xưng", new ImageIcon(getClass().getResource("/img/user.png"))));
        txtSearchCD.addOption(new SearchOption("thời gian", new ImageIcon(getClass().getResource("/img/user.png"))));

    }
    void AddSearchTLV() {
        txtSearchCTH.addEventOptionSelected(new SearchOptinEvent() {
            @Override
            public void optionSelected(SearchOption option, int index) {
                txtSearchCTH.setHint("Tìm kiếm " + option.getName() + "....");
            }
        });
        txtSearchCTH.addOption(new SearchOption("tên bài", new ImageIcon(getClass().getResource("/img/user.png"))));


    }
}
